# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [2]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

l_3 = l_1 + l_2
print(l_3)
print(f"Summation of a regular python list: {l_1 + l_2}")
print(f"Subtraction of a regular python list: {l_1 - l_2}")

[1, 2, 3, 4, 5, 6]
Summation of a regular python list: [1, 2, 3, 4, 5, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [11]:
l1 = [2,3,4]
l2 = [1,5,2]

def addlist(l1, l2):
    l = []
    for x in range(len(l1)):
        l.append(l1[x] + l2[x])
    return l
addlist(l1, l2)

[3, 8, 6]

#### Importing

In [3]:
# always import as np, standard across all of data science
# !pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [15]:
arr1 = np.array([1,2,3])
arr1
print(type(arr1))

<class 'numpy.ndarray'>


###### - np.zeros()

In [17]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeroes = np.zeros((3,3))
arr_zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [19]:
arr_ones = np.ones((3,3))
arr_ones_int = np.ones((3,3), int)
arr_ones_int

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### - np.arange()

In [7]:
arr_range = np.arange(1,12)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###### - Making Lists into NDArrays

In [23]:
l1 = [5,6,7]
l1 = np.array(l1)
l1

array([5, 6, 7])

#### Performing Calculations on NDArrays

###### - Summation

In [25]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10, 20, 30, 40 ,50])

result = arr_list1 + arr_list2
result

array([15, 30, 45, 60, 75])

###### - Difference

In [27]:
result_ = arr_list2 - arr_list1
result_

array([ 5, 10, 15, 20, 25])

###### - Multiplication

In [78]:
resultM = arr_list1 * arr_list2
resultM

array([  50,  200,  450,  800, 1250])

###### - Division

In [29]:
resultD = arr_list1 / arr_list2
resultD

array([0.5, 0.5, 0.5, 0.5, 0.5])

#### Modulo

In [31]:
resultMod = arr_list2 % arr_list1
resultMod

array([0, 0, 0, 0, 0], dtype=int32)

#### Floor Division

In [32]:
resultF = arr_list2 // arr_list1
resultF

array([2, 2, 2, 2, 2], dtype=int32)

#### Numpy Subsetting

In [37]:
# result3 <= 800
print(resultM <= 800)
print(resultM[resultM <= 800])

# test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
# print(test_ndStrings[test_ndStrings[0] == 'B'])

# conditioal check, returns true or false
print(arr_list1 < 2)
print(arr_list2 >= 2)

# conditional check, that returns the elements that meet the given condition


[ True  True  True  True False]
[ 50 200 450 800]
[False False False False False]
[ True  True  True  True  True]


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [39]:
a = [0,1,2]
b = [3,4,5]
c = [6,7,8]

# first step: convert lists into a Matrix
M = [a, b, c]
M
print(M[1][1])



# second step: place Matrix inside NDArray
ndm = np.array(M)
print(ndm)

4
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [40]:
print(f"Getting the middle element within the matrix: {ndm[1,1]}")

Getting the middle element within the matrix: 4


#### Assigning Values in NDArrays

In [41]:
ndm[1,1] = 9
ndm

array([[0, 1, 2],
       [3, 9, 5],
       [6, 7, 8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [42]:
# usind the .dtype() method
ndtype = ndm.dtype
ndtype

dtype('int32')

#### Altering NDArray Type

In [44]:
resulttype = ndtype
print(f"Type before change: {resulttype}")

changed = ndm.astype(np.float32)
resultchanged = changed
print(f"Type after change: {resultchanged.dtype}\n{changed}")

Type before change: int32
Type after change: float32
[[0. 1. 2.]
 [3. 9. 5.]
 [6. 7. 8.]]


In [ ]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [45]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape
resultchanged.shape
# print(type(result_changed.shape))

(3, 3)

#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [50]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column
print(resultchanged.reshape(1,9))
print(resultchanged.reshape(9,1))

[[0. 1. 2. 3. 9. 5. 6. 7. 8.]]
[[0.]
 [1.]
 [2.]
 [3.]
 [9.]
 [5.]
 [6.]
 [7.]
 [8.]]


In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [55]:
"""
OUTPUT
    array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""
import numpy as np
a1 = [0,1,2,3]
b1 = [4,5,6,7]
c1 = [8,9,10,11]
d1 = [12,13,14,15]
# first step: convert lists into a Matrix
M1= [a1, b1, c1, d1]
ndm1 = np.array(M1)
ndm1

my_arr = np.arange(0,16)
my_arr.reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Complex Indexing & Assinging

In [66]:
M = np.zeros((6,6))
print("Resetting Matrix\nBefore Assignment")
print(M)

# Set every first element in each row to 1
M[:,0]=1
print("\n After assigning 1 to the first column")
print(M)
# Set all elements in axis 3 to 5 (Excluding 5) to be equal to the number 5
M[2:5,:]=5
print("\n After assigning 5 to the rows 3-5")
print(M)

# reset the matrix back to 0
print("\n Reset to 0's")
M = M * 0
print(M)

# Set the second and third columns to a number == 2
M[:,1:3]=2
print("\n After assigning 2 to the columns 2-3")
print(M)

# Creating a vector in numpy
x = np.arange(6)

# Reset the Matrix to 0
M *= 0

# Set the first row to that range of vector numbers we just created
M[0,:] = x
print("\nAssigning Vector Array X to the first axis of the matrix")
print(M)

#################
# M[rows,columns]
#################

Resetting Matrix
Before Assignment
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 After assigning 1 to the first column
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

 After assigning 5 to the rows 3-5
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]]

 Reset to 0's
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 After assigning 2 to the columns 2-3
[[0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]]

Assigning Vector Array X to the first axis of the matrix
[[0. 1. 2. 3. 4. 5.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [71]:
# Initialize a vector of range 6, then reset Matrix to zero and run vector multiplication on the matrix
v = M[:,:] = 0
print(v)

# Reset the Matrix to 0
M *= v
print(M)

0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [79]:
print(resultM)
print("\n", np.where(resultM < 800))
print("\n", resultM[np.where(resultM < 800)])
# Transform Data based on boolean mask == True
resultM[np.where(resultM < 800)] = 300
print("\n", resultM)

[  50  200  450  800 1250]

 (array([0, 1, 2], dtype=int64),)

 [ 50 200 450]

 [ 300  300  300  800 1250]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [80]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.5328376644628594
Here is a random number between 0 and 1 Million: 592791.5761160859
Here are 5 random numbers between 0 and 10: [4.74504355 8.80883136 0.33000702 5.69384827 1.53095259]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[0.07719597 2.54419683 2.37116263]
 [1.71067027 7.9835626  0.55928298]
 [2.73529869 6.74812601 0.03265824]]


## Working With CSV's

#### Imports

In [82]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [83]:
# Creating Function to open and read CSV data
def openCSV(filename, d=","):
    data = []
    with open(filename, encoding="utf-8") as mdata:
        # use the csv reader method to create a python list
        info = csv.reader(mdata, delimiter=d)
        for row in info:
            data.append(row)
    return data
csvdata = openCSV("files/boston_marathon2017_edited.csv")
print(csvdata[1:5])

[['12/30/1899 12:30:28 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:02:53 AM', '12/30/1899 12:15:25 AM', '24', '11', '7777', 'KEN', '7777', '', 'Keringet', 'KEN', '1', '1', '12/30/1899 1:04:35 AM', 'M', 'Kirui, Geoffrey', '1', '12/30/1899 2:09:37 AM', '1', '12/30/1899 12:04:57 AM', ''], ['12/30/1899 12:30:27 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:03:14 AM', '12/30/1899 12:15:24 AM', '30', '17', '7798', 'USA', '7798', '', 'Portland', 'USA', '2', '2', '12/30/1899 1:04:35 AM', 'M', 'Rupp, Galen', '1', '12/30/1899 2:09:58 AM', '2', '12/30/1899 12:04:58 AM', 'OR'], ['12/30/1899 12:30:29 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:16 AM', '12/30/1899 1:17:00 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:31 AM', '12/30/1899 2:03:38 AM', '12/30/1899 12:15:25 AM', '25', '23', '7828', 'JP

#### Loading a CSV's Data 

In [90]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on
def loadData(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, skip_header=1,
                        usecols=np.arange(0,24), invalid_raise=False,
                        names=FIELDS, dtype=DATATYPES)
    return data
bs2017 = loadData("./files/redsox_2017_hitting.txt")
names = bs2017["Name"]
print(names)
print(bs2017)

# Find the total number of Hits
totalHits = sum(bs2017["H"])
print(f"\nTotal Hits: {totalHits}")
totalHR = sum(bs2017["HR"])
print(f"\nTotal HR: {totalHR}")

[b'Christian Vazquez' b'Mitch Moreland' b'Dustin Pedroia'
 b'Xander Bogaerts' b'Rafael Devers' b'Andrew Benintendi'
 b'Jackie Bradley Jr.' b'Mookie Betts' b'Hanley Ramirez' b'Sandy Leon'
 b'Chris Young' b'Deven Marrero' b'Eduardo Nunez' b'Brock Holt'
 b'Josh Rutledge' b'Pablo Sandoval' b'Sam Travis' b'Tzu-Wei Lin'
 b'Marco Hernandez' b'Rajai Davis' b'Steve Selsky' b'Blake Swihart'
 b"Chase d'Arnaud"]
[( 1, b'C', b'Christian Vazquez', 26,  99, 345, 324,  43,  94, 18, 2,  5,  32,  7, 2, 17,  64, 0.29 , 0.33 , 0.404, 0.735,  91, 131, 14)
 ( 2, b'1B', b'Mitch Moreland', 31, 149, 576, 508,  73, 125, 34, 0, 22,  79,  0, 1, 57, 120, 0.246, 0.326, 0.443, 0.769,  99, 225, 14)
 ( 3, b'2B', b'Dustin Pedroia', 33, 105, 463, 406,  46, 119, 19, 0,  7,  62,  4, 3, 49,  48, 0.293, 0.369, 0.392, 0.76 , 100, 159, 11)
 ( 4, b'SS', b'Xander Bogaerts', 24, 148, 635, 571,  94, 156, 32, 6, 10,  62, 15, 1, 56, 116, 0.273, 0.343, 0.403, 0.746,  95, 230, 17)
 ( 5, b'3B', b'Rafael Devers', 20,  58, 240, 222,  34

#### Summing the top 5 hitters for HR's

In [97]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
allHR = bs2017["HR"]

# Step 2
allNames = bs2017["Name"]

# Step 3
newNames = []

# Step 4
for name in range(len(allNames)):
    newNames.append(allNames[name].decode("utf-8"))
# print(newNames)

# Step 5
zippedValues = list(zip(newNames, allHR))
# print(zippedValues)

# Step 6
sortedHR = sorted(zippedValues, key=lambda x:x[1], reverse=True)
print(sortedHR[0:5])

[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17)]


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>